approvedGitRepositories:
  - "**"

enableScripts: true

logFilters:
  - code: YN0002
    level: discard
    text: doesn't provide jest
  - code: YN0060
    level: discard
    text: "@material-ui/core and other dependencies request"
  - code: YN0086
    level: discard
    text: Some peer dependencies are incorrectly met

npmMinimalAgeGate: 0

packageExtensions:
  "@backstage/cli-module-test-jest@*":
    dependencies:
      "@jest/environment-jsdom-abstract": "*"
      jest-environment-node: "*"
      jest-runtime: "*"
      jsdom: "*"
      yaml: "*"
  "@backstage/cli-module-build@*":
    dependencies:
      esbuild: ^0.28.1
  "@backstage/plugin-app@*":
    dependencies:
      "@backstage/config": ^1.3.8
      "@backstage/core-app-api": ^1.20.2
      i18next: ^26.3.6
      lodash: ^4.18.1
      prop-types: ^15.8.1
      use-sync-external-store: ^1.5.0
  "@backstage/plugin-catalog-react@*":
    dependencies:
      "@emotion/react": ^11.14.0
      "@emotion/styled": ^11.14.1
      "@mui/material": ^7.3.11
  "@backstage/plugin-permission-react@*":
    dependencies:
      react-router: ^6.30.4
      react-router-dom: ^6.30.4
  typescript@*:
    peerDependencies:
      vitest: "*"
  vitest@*:
    dependencies:
      "@types/node": "*"

plugins:
  - checksum: 0cfdc882d3c1395592aa6d4690958e70ebbc3a8ee1d888d523dc9e3c74796de26f744c37df66a69212280634f422a88074ba625dce0f7886fbdf2a904a0c38a2
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.52.1/yarn-plugin"
