# yaml-language-server: $schema=https://backstage.io
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: 'development-modern.sqlite'
