/*
 * Copyright 2026 The AI Crew Suite Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import type { Embeddings } from '@langchain/core/embeddings';
import type { EmbeddingDocMetadata } from '../sources';
import type { EmbeddingDoc } from '../pipelines';

/**
 * ============================================================================
 *   REGISTRATION BLUEPRINTS (Extension Point Definitions)
 * ============================================================================
 */

/**
 * Registers an embeddings provider module for runtime vectorization.
 */
export type EmbeddingsDefinition = {
  /** Unique provider identifier (e.g. `openai`, `aws-bedrock`). */
  id: string;
  /** LangChain text embedding model adapter instance used for spatial analysis. */
  embeddings: Embeddings;
};

/**
 * Registers a retrieval reranking provider module (e.g. Cohere Rerank).
 */
export type RerankingDefinition = {
  /** Unique provider identifier. */
  id: string;
  /** Refines similarity search hits based on precise contextual query matching. */
  rerank(input: {
    query: string;
    documents: { id: string; text: string }[];
  }): Promise<{ id: string; score: number }[]>;
};

/**
 * Structural definition mapping an active vector store strategy wrapper.
 */
export type VectorStoreDefinition = {
  /** Stable identifier of the vector storage driver (e.g. `pgvector`, `qdrant`). */
  id: string;
  /** Concrete instance of the vector store engine wrapper. */
  store: VectorStore;
};

/**
 * ============================================================================
 *   RUNTIME DATABASES & DATA STRUCTURES (Runtime Operations)
 * ============================================================================
 */

/**
 * Persisted embedding record containing source text and its vector representation.
 */
export type Embedding = {
  /** Metadata used for filtering, attribution, and traceability. */
  metadata: EmbeddingDocMetadata;
  /** Original text content represented by the vector. */
  content: string;
  /** Numeric embedding vector generated by the configured embedding model. */
  vector: number[];
  /** Stable document identifier in the vector store. */
  id: string;
};

/**
 * Parameters used to delete documents from a vector store.
 */
export type DeletionParams = {
  /** Optional explicit document IDs to delete. */
  ids?: string[];
  /** Optional metadata filter used to delete matching documents. */
  filter?: EmbeddingDocMetadata;
};

/**
 * Minimal vector-store contract used by indexers and retrievers.
 */
export interface VectorStore {
  /** Connects the LangChain embeddings implementation used for vector operations. */
  connectEmbeddings(embeddings: Embeddings): void;
  /** Adds or updates embedded documents in the store. */
  addDocuments(docs: EmbeddingDoc[]): Promise<void>;
  /** Deletes documents by ID and/or metadata filter. */
  deleteDocuments(deletionParams: DeletionParams): Promise<void>;
  /** Returns the most similar documents for a natural-language query. */
  similaritySearch(
    query: string,
    filter?: EmbeddingDocMetadata,
    amount?: number,
  ): Promise<EmbeddingDoc[]>;
}
