/*
 * Copyright 2026 The AI Crew Suite Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { LoggerService } from '@backstage/backend-plugin-api';
import type { BaseChatModel } from '@langchain/core/language_models/chat_models';
import type { AgentDefinition, AgentEvent } from '../agents';
import type { ToolRegistry } from '../tools/core';
import type { SourceId, EntityFilterShape } from '../sources';
import type {
  RunStore,
  SessionStore,
  CheckpointStore,
  ArtifactSink,
  AuditLogSink,
  ApprovalDecision,
} from '../storage/runtime';

/**
 * ============================================================================
 *   MACRO RUN-LEVEL RUNNERS & ORCHESTRATION INPUTS
 * ============================================================================
 */

/**
 * Input required to start an agent run.
 */
export type AgentRunInput = {
  /** Unique run identifier generated by the caller or controller. */
  runId: string;
  /** Agent identifier to execute. */
  agentId: string;
  /** Optional idempotency key used to deduplicate external trigger requests. */
  idempotencyKey?: string;
  /** Optional trigger name or source that initiated the run. */
  trigger?: string;
  /** User and retrieval inputs supplied to the agent. */
  input: {
    /** Natural-language task or question for the agent. */
    query: string;
    /** Source to use for retrieval augmentation. */
    source: SourceId;
    /** Optional conversation session ID for memory-enabled agents. */
    sessionId?: string;
    /** Optional entity/document filter passed to retrieval tools. */
    entityFilter?: EntityFilterShape;
  };
};

/**
 * A domain-specific workflow graph registered by an agent plugin.
 */
export interface WorkflowRunner {
  /** Stable ID referenced by `AgentDefinition.workflowRef`. */
  readonly id: string;
  /** Executes the domain workflow and emits standard AI Core events. */
  run(input: AgentRunInput, context: WorkflowContext): AsyncIterable<AgentEvent>;
  /** Resumes a paused workflow when it supports approvals or checkpoints. */
  resume?(
    runId: string,
    decision: ApprovalDecision,
    context: WorkflowContext,
  ): AsyncIterable<AgentEvent>;
}

/**
 * ============================================================================
 *   RUN-LEVEL LIFECYCLE FACADES
 * ============================================================================
 */

/**
 * Context supplied to a registered domain workflow runner.
 *
 * Workflows receive this controlled facade instead of raw tool or model maps.
 */
export type WorkflowContext = RunContext & {
  agent: AgentDefinition;
  invokeTool<TArgs = unknown, TResult = unknown>(input: {
    toolId: string;
    args: TArgs;
    limits?: ToolInvocationLimits;
  }): Promise<ToolInvocationResult<TResult>>;
};

/**
 * Runtime services and policy supplied to an orchestrator for a single run.
 */
export type RunContext = {
  /** Logger scoped to the backend runtime. */
  logger: LoggerService;
  /** Registry of tools available to the current run. */
  toolRegistry: ToolRegistry;
  /** Language model selected for the current agent run. */
  model: BaseChatModel;
  /** Optional system prompt applied by the workflow when calling the model. */
  systemPrompt?: string;
  /** Verified actor identity for tool context, audit logs, and session ownership. */
  identity: string;
  /** Optional cancellation signal for long-running model or tool work. */
  signal?: AbortSignal;
  /** Optional session memory store for conversation history. */
  sessionStore?: SessionStore;
  /** Optional checkpoint store for resumable orchestration. */
  checkpointStore?: CheckpointStore;
  /** Optional run store for lifecycle persistence and event replay. */
  runStore?: RunStore;
  /** Optional sink for artifacts emitted by orchestrators. */
  artifactSink?: ArtifactSink;
  /** Optional sink for write-action audit records. */
  auditLogSink?: AuditLogSink;
  /** Optional runtime hardening limits and retry policy. */
  hardening?: {
    /** Maximum run duration in milliseconds before cancellation. */
    timeoutMs?: number;
    /** Maximum number of retries for retryable orchestration failures. */
    maxRetries?: number;
    /** Base delay in milliseconds between retries. */
    retryBackoffMs?: number;
    /** Maximum total tokens allowed for a run before it is stopped. */
    maxTotalTokens?: number;
    /** Maximum number of tools a workflow may invoke during one run. */
    maxToolInvocations?: number;
    /** Maximum duration of one tool invocation in milliseconds. */
    toolTimeoutMs?: number;
  };
  /** Memory mode selected for the current agent. */
  memory?: 'none' | 'session';
};

/**
 * Global open-ended schema registry matching the Backstage module federation pattern.
 * Each of the 18 workflow plugins will use module augmentation to attach their specific
 * Zod configurations here.
 */
export interface AiAgentSchemaRegistry {
  // Purposely empty. Populated at runtime dynamically by sub-plugins.
}

/**
 * ============================================================================
 *   MICRO-LEVEL GRAPH NODE CONTEXTS
 * ============================================================================
 */

/**
 * The plugin-facing facade for node execution. This is the ONLY interface plugins may
 * use to invoke tools/models, emit artifacts, observe time, or log. Provided by the engine.
 */
export type NodeExecutionContext = {
  /** Run-scoped logger; all lines carry runId + node. */
  logger: LoggerService;
  /** The only path to tools from within this specific vertex execution loop. */
  tools: ToolExecutor;
  /** The only path to models from within this specific vertex execution loop. */
  model: ModelExecutor;
  /** Emit a typed artifact event + persist. Kind must be declared on the workflow. */
  emitArtifact(kind: string, payload: { ref?: string; url?: string }): Promise<void>;
  /** Deterministic clock (injectable; defaults to Date). Tests freeze it. */
  now(): Date;
  /** Abort signal honoring run cancellation and per-node timeouts. */
  signal: AbortSignal;
};

/**
 * ============================================================================
 *   STEP EXECUTOR EXECUTABLE PRIMITIVES
 * ============================================================================
 */

/**
 * The only path to tools from within a workflow node. Enforces allow-lists, provider
 * policy, RBAC filtering, effect gating, budgets, and audit. Provided by the engine.
 */
export type ToolExecutor = {
  invoke<TArgs = unknown, TResult = unknown>(input: {
    toolId: string;
    args: TArgs;
    limits?: ToolInvocationLimits;
  }): Promise<ToolInvocationResult<TResult>>;
  /**
   * Scatter-gather over all providers allowed for this call. Opt-in per category;
   * a category must declare `supportsScatterGather`. Per-provider failures captured.
   */
  invokeAll?<TArgs = unknown, TResult = unknown>(input: {
    toolId: string;
    args: TArgs;
    limits?: ToolInvocationLimits;
  }): Promise<ToolInvocationResult<TResult>[]>;
};

/**
 * The only path to models from within a workflow node. Streams tokens as events and
 * enforces token budgets. Provider-neutral; resolved from the agent's modelRef or a tier.
 */
export type ModelExecutor = {
  stream(input: { messages: ChatMessage[]; tools?: ToolSpec[] }): AsyncIterable<ModelChunk>;
  invoke(input: { messages: ChatMessage[] }): Promise<string>;
  /** Returns an executor bound to a named tier (`fast` / `reasoning` / ...). */
  forTier(tier: string): ModelExecutor;
};

/**
 * A chat-model message in `ModelExecutor` requests.
 */
export type ChatMessage = { role: 'system' | 'user' | 'assistant'; content: string };

/** A JSON-schema tool spec passed to models that support tool-calling. */
export type ToolSpec = {
  name: string;
  description?: string;
  schema?: unknown;
};

/**
 * A single streamed chunk emitted by a model execution step.
 */
export type ModelChunk = {
  text?: string;
  toolCalls?: { id: string; name: string; args: unknown }[];
  usage?: { input: number; output: number; total: number };
};
