/*
 * Copyright 2026 Webstack Builders, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { EmbeddingDocMetadata } from './source';
import { EmbeddingDoc } from './rag';
import type { Embeddings } from '@langchain/core/embeddings';

/**
 * Persisted embedding record containing source text and its vector representation.
 */
export type Embedding = {
  /** Metadata used for filtering, attribution, and traceability. */
  metadata: EmbeddingDocMetadata;
  /** Original text content represented by the vector. */
  content: string;
  /** Numeric embedding vector generated by the configured embedding model. */
  vector: number[];
  /** Stable document identifier in the vector store. */
  id: string;
};

/**
 * Parameters used to delete documents from a vector store.
 */
export type DeletionParams = {
  /** Optional explicit document IDs to delete. */
  ids?: string[];
  /** Optional metadata filter used to delete matching documents. */
  filter?: EmbeddingDocMetadata;
};

/**
 * Minimal vector-store contract used by indexers and retrievers.
 */
export interface VectorStore {
  /** Connects the LangChain embeddings implementation used for vector operations. */
  connectEmbeddings(embeddings: Embeddings): void;
  /** Adds or updates embedded documents in the store. */
  addDocuments(docs: EmbeddingDoc[]): Promise<void>;
  /** Deletes documents by ID and/or metadata filter. */
  deleteDocuments(deletionParams: DeletionParams): Promise<void>;
  /** Returns the most similar documents for a natural-language query. */
  similaritySearch(
    query: string,
    filter?: EmbeddingDocMetadata,
    amount?: number,
  ): Promise<EmbeddingDoc[]>;
}
