/*
 * Copyright 2024 Larder Software Limited
 * Copyright 2026 Webstack Builders, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Embeddings } from '@langchain/core/embeddings';
import { BaseChatModel } from '@langchain/core/language_models/chat_models';
import { BaseLLM } from '@langchain/core/language_models/llms';
import { LoggerService } from '@backstage/backend-plugin-api';

/**
 * Stable identifier for a retrieval or indexing source, such as `catalog`,
 * `techdocs`, or a custom source contributed by another backend module.
 */
export type SourceId = string;

/**
 * Source identifier used by embedding, indexing, and retrieval APIs.
 */
export type EmbeddingsSource = SourceId;

/**
 * Describes a source that can provide content for embedding and retrieval.
 */
export type SourceDescriptor = {
  /** Unique source identifier used in config, API requests, and retrieval filters. */
  id: SourceId;
  /** Human-readable description of the source and the content it represents. */
  description?: string;
};

/**
 * Registry of source descriptors known to the AI backend runtime.
 */
export interface SourceRegistry {
  /** Adds a source descriptor to the registry. Implementations should reject duplicate IDs. */
  register(source: SourceDescriptor): void;
  /** Returns all registered sources in registry order. */
  list(): SourceDescriptor[];
  /** Returns whether a source with the supplied ID has been registered. */
  has(id: SourceId): boolean;
}

/**
 * Metadata stored alongside an embedded document.
 *
 * Values are strings so they can be passed through common vector-store filter
 * implementations without needing source-specific serialization logic.
 */
export type EmbeddingDocMetadata = Partial<{
  /** Source that produced the document. */
  source: EmbeddingsSource;
  /** Additional source-specific metadata, such as entity refs, owners, or URLs. */
  [key: string]: string;
}>;

/**
 * Optional Backstage entity-style filter accepted by indexing and retrieval APIs.
 */
export type EntityFilterShape =
  | Record<string, string | symbol | (string | symbol)[]>[]
  | Record<string, string | symbol | (string | symbol)[]>
  | undefined;

/**
 * Persisted embedding record containing source text and its vector representation.
 */
export type Embedding = {
  /** Metadata used for filtering, attribution, and traceability. */
  metadata: EmbeddingDocMetadata;
  /** Original text content represented by the vector. */
  content: string;
  /** Numeric embedding vector generated by the configured embedding model. */
  vector: number[];
  /** Stable document identifier in the vector store. */
  id: string;
};

/**
 * Text document returned from retrieval and passed to language-model prompts.
 */
export type EmbeddingDoc = {
  /** Metadata used to identify and filter the retrieved document. */
  metadata: EmbeddingDocMetadata;
  /** Retrieved document text that can be included as grounding context. */
  content: string;
};

/**
 * Creates and removes embeddings for a content source.
 */
export interface AugmentationIndexer {
  /** Vector store used by the indexer to persist generated embedding documents. */
  vectorStore: VectorStore;
  /**
   * Generates embeddings for documents from the source and returns the number
   * of embedded documents written to the vector store.
   */
  createEmbeddings(
    source: EmbeddingsSource,
    filter?: EntityFilterShape,
  ): Promise<number>;
  /** Removes embeddings for the source and optional entity/document filter. */
  deleteEmbeddings(
    source: EmbeddingsSource,
    filter: EntityFilterShape,
  ): Promise<void>;
}

/**
 * Selects one or more retrievers that should handle a query for a source.
 */
export interface RetrievalRouter {
  /** Returns the retrievers to execute for the supplied query and source. */
  determineRetriever(
    query: string,
    source: EmbeddingsSource,
  ): Promise<AugmentationRetriever[]>;
}

/**
 * Retrieves grounding documents for a query from a source-specific backend.
 */
export interface AugmentationRetriever {
  /** Unique retriever identifier used for diagnostics and result grouping. */
  id: string;
  /** Returns documents relevant to the query, source, and optional filter. */
  retrieve(
    query: string,
    source: EmbeddingsSource,
    filter?: EntityFilterShape,
  ): Promise<EmbeddingDoc[]>;
}

/**
 * Combines, ranks, filters, or otherwise transforms retriever outputs.
 */
export interface AugmentationPostProcessor {
  /** Produces the final retrieval context from retriever results keyed by retriever ID. */
  process(
    query: string,
    source: EmbeddingsSource,
    embeddingDocs: Map<string, EmbeddingDoc[]>,
  ): Promise<EmbeddingDoc[]>;
}

/**
 * End-to-end retrieval pipeline used by tools and controllers to gather context.
 */
export interface RetrievalPipeline {
  /** Returns documents that should be supplied to an agent as augmentation context. */
  retrieveAugmentationContext(
    query: string,
    source: EmbeddingsSource,
    filter?: EntityFilterShape,
  ): Promise<EmbeddingDoc[]>;
}

/**
 * Parameters used to delete documents from a vector store.
 */
type DeletionParams = {
  /** Optional explicit document IDs to delete. */
  ids?: string[];
  /** Optional metadata filter used to delete matching documents. */
  filter?: EmbeddingDocMetadata;
};

/**
 * Minimal vector-store contract used by indexers and retrievers.
 */
export interface VectorStore {
  /** Connects the LangChain embeddings implementation used for vector operations. */
  connectEmbeddings(embeddings: Embeddings): void;
  /** Adds or updates embedded documents in the store. */
  addDocuments(docs: EmbeddingDoc[]): Promise<void>;
  /** Deletes documents by ID and/or metadata filter. */
  deleteDocuments(deletionParams: DeletionParams): Promise<void>;
  /** Returns the most similar documents for a natural-language query. */
  similaritySearch(
    query: string,
    filter?: EmbeddingDocMetadata,
    amount?: number,
  ): Promise<EmbeddingDoc[]>;
}

/**
 * Registers a language model that agents can reference by ID.
 */
export type ModelDefinition = {
  /** Unique model identifier used by agent definitions and crew roles. */
  id: string;
  /** LangChain LLM or chat model instance used for generation. */
  model: BaseLLM | BaseChatModel;
};

/**
 * Binds an external trigger source to an optional default agent.
 */
export type TriggerBinding = {
  /** Unique trigger identifier, such as `github-pr-opened` or `nightly-scan`. */
  id: string;
  /** Optional source name associated with the trigger payload. */
  source?: string;
  /** Optional agent to run when this trigger fires. */
  agentId?: string;
};

/**
 * Declarative profile for an agent that can be executed by the AI runtime.
 */
export type AgentDefinition = {
  /** Unique agent identifier used in API routes, triggers, and run records. */
  id: string;
  /** Model ID from the model registry that should be used by default. */
  modelRef: string;
  /** System prompt applied to the agent's model calls. */
  systemPrompt: string;
  /** Tool IDs the agent is allowed to use. */
  toolIds: string[];
  /** Orchestration strategy used to execute the agent. Defaults are runtime-defined. */
  orchestrator?: 'single-shot' | 'langgraph' | 'crew';
  /** Memory mode for the agent. `session` enables persisted conversational history. */
  memory?: 'none' | 'session';
  /** Optional crew configuration for multi-role sequential orchestration. */
  crew?: {
    /** Ordered roles executed by the crew orchestrator. */
    roles: {
      /** Unique role identifier within the agent's crew. */
      id: string;
      /** System prompt used for this role's model call. */
      systemPrompt: string;
      /** Optional model override for this role. Falls back to the agent model when omitted. */
      modelRef?: string;
      /** Optional tool allow-list override for this role. */
      toolIds?: string[];
    }[];
  };
  /** Optional trigger bindings that can start this agent. */
  triggers?: TriggerBinding[];
};

/**
 * Runtime context provided to a tool invocation.
 */
export type ToolContext = {
  /** Optional credentials object supplied by the caller or host integration. */
  credentials?: unknown;
  /** Optional auth helper supplied by the host application. */
  auth?: unknown;
  /** Optional discovery helper supplied by the host application. */
  discovery?: unknown;
  /** Logger scoped to the current backend runtime. */
  logger: LoggerService;
  /** Identity ref or label for the actor that started the run. */
  identity: string;
  /** Run identifier used for tracing and audit correlation. */
  runId: string;
  /** Abort signal that tools should observe for cancellation and timeout handling. */
  signal: AbortSignal;
};

/**
 * Executable tool that can be invoked by an agent or orchestration pipeline.
 */
export interface Tool<A = unknown, R = unknown> {
  /** Unique tool identifier used by agent definitions and events. */
  id: string;
  /** Human-readable summary of the tool's behavior. */
  description?: string;
  /** Optional input schema understood by clients or validation layers. */
  schema?: unknown;
  /** Executes the tool with caller-provided arguments and runtime context. */
  invoke(args: A, ctx: ToolContext): Promise<R>;
  /** Declares whether the tool only reads data or may modify external systems. */
  effect?: 'read' | 'write';
}

/**
 * Registry of tools available to orchestrators and agents.
 */
export interface ToolRegistry {
  /** Adds a tool to the registry. Implementations should reject duplicate IDs. */
  register(tool: Tool): void;
  /** Returns a tool by ID, or `undefined` when it is not registered. */
  get(id: string): Tool | undefined;
  /** Returns all registered tools in registry order. */
  list(): Tool[];
}

/**
 * Tool registration shape used by backend modules.
 */
export type ToolDefinition = Tool & {
  /** Optional indexer exposed by this tool for embedding creation and deletion. */
  augmentationIndexer?: AugmentationIndexer;
  /** Optional retrieval pipeline exposed by this tool for augmentation lookups. */
  retrievalPipeline?: RetrievalPipeline;
};

/**
 * Input required to start an agent run.
 */
export type AgentRunInput = {
  /** Unique run identifier generated by the caller or controller. */
  runId: string;
  /** Agent identifier to execute. */
  agentId: string;
  /** Optional idempotency key used to deduplicate external trigger requests. */
  idempotencyKey?: string;
  /** Optional trigger name or source that initiated the run. */
  trigger?: string;
  /** User and retrieval inputs supplied to the agent. */
  input: {
    /** Natural-language task or question for the agent. */
    query: string;
    /** Source to use for retrieval augmentation. */
    source: SourceId;
    /** Optional conversation session ID for memory-enabled agents. */
    sessionId?: string;
    /** Optional entity/document filter passed to retrieval tools. */
    entityFilter?: EntityFilterShape;
  };
};

/**
 * Persisted conversational message for session memory.
 */
export type SessionMessage = {
  /** Role that authored the message. */
  role: 'user' | 'assistant' | 'system';
  /** Message text content. */
  content: string;
  /** Optional token accounting associated with this message. */
  tokenUsage?: {
    /** Number of input tokens consumed. */
    input: number;
    /** Number of output tokens produced. */
    output: number;
    /** Total token count for the operation. */
    total: number;
  };
  /** Optional ISO timestamp for when the message was created. */
  createdAt?: string;
};

/**
 * Store for persisted agent conversation sessions.
 */
export interface SessionStore {
  /** Creates a new session for an agent and optional user, returning its ID. */
  createSession(agentId: string, userRef?: string): Promise<string>;
  /** Appends a message to an existing session. */
  appendMessage(sessionId: string, message: SessionMessage): Promise<void>;
  /** Lists recent messages for a session, optionally limited by count. */
  listMessages(sessionId: string, limit?: number): Promise<SessionMessage[]>;
}

/**
 * Store for resumable orchestration state.
 */
export interface CheckpointStore {
  /** Saves arbitrary checkpoint state for a run. */
  save(runId: string, state: unknown): Promise<void>;
  /** Loads checkpoint state for a run, or `undefined` when no checkpoint exists. */
  load<T = unknown>(runId: string): Promise<T | undefined>;
}

/**
 * Persisted summary record for an agent run.
 */
export type RunRecord = {
  /** Unique run identifier. */
  id: string;
  /** Agent executed by the run. */
  agentId: string;
  /** Optional session associated with the run. */
  sessionId?: string;
  /** Current lifecycle status for the run. */
  status: 'running' | 'paused' | 'done' | 'error';
  /** Optional trigger source that started the run. */
  trigger?: string;
  /** Optional idempotency key used to deduplicate run creation. */
  idempotencyKey?: string;
};

/**
 * Persisted event emitted during an agent run.
 */
export type RunStepRecord = {
  /** Monotonic sequence number for replaying events in order. */
  seq: number;
  /** Event type name. */
  type: string;
  /** Serialized event payload. */
  payload: unknown;
};

/**
 * Artifact produced by an agent run.
 */
export type Artifact = {
  /** Unique artifact identifier. */
  id: string;
  /** Run that produced the artifact. */
  runId: string;
  /** Artifact category, such as `doc`, `draft`, or `final_answer`. */
  kind: string;
  /** Optional stable reference name for the artifact. */
  ref?: string;
  /** Optional URL where the artifact can be retrieved. */
  url?: string;
};

/**
 * Sink for recording artifacts produced by runs.
 */
export interface ArtifactSink {
  /** Persists or forwards an artifact record. */
  record(artifact: Artifact): Promise<void>;
}

/**
 * Audit record for write actions and approval decisions.
 */
export type AuditLogEntry = {
  /** Unique audit entry identifier. */
  id: string;
  /** Run associated with the audited action. */
  runId: string;
  /** Agent associated with the audited action. */
  agentId: string;
  /** Action name, such as `write_tool_call` or `approval_approved`. */
  action: string;
  /** Optional tool ID involved in the action. */
  toolId?: string;
  /** Optional sanitized payload for diagnostics and compliance review. */
  payload?: unknown;
  /** Optional actor identity that initiated or approved the action. */
  actor?: string;
};

/**
 * Sink for recording auditable write-related actions.
 */
export interface AuditLogSink {
  /** Records an auditable write action, approval decision, or artifact write. */
  recordWriteAction(entry: AuditLogEntry): Promise<void>;
}

/**
 * Human decision for a pending approval request.
 */
export type ApprovalDecision = {
  /** Whether the requested action is allowed to continue. */
  status: 'approved' | 'rejected';
  /** Optional reviewer note explaining the decision. */
  note?: string;
  /** Optional identity of the reviewer who made the decision. */
  decidedBy?: string;
};

/**
 * Pending approval request emitted when an agent needs human authorization.
 */
export type ApprovalRequest = {
  /** Unique approval identifier. */
  id: string;
  /** Run waiting on this approval. */
  runId: string;
  /** Human-readable reason approval is required. */
  reason: string;
  /** Effect level of the pending action. */
  effect: 'read' | 'write';
};

/**
 * Store for run lifecycle, event replay, and approval state.
 */
export interface RunStore {
  /** Creates the initial persisted record for a run. */
  createRun(record: RunRecord): Promise<void>;
  /** Returns a run record by ID, or `undefined` when not found. */
  getRun(runId: string): Promise<RunRecord | undefined>;
  /** Returns a run previously created with the idempotency key, if any. */
  findRunByIdempotencyKey(key: string): Promise<RunRecord | undefined>;
  /** Updates the lifecycle status for a run. */
  updateRunStatus(runId: string, status: RunRecord['status']): Promise<void>;
  /** Appends an event payload to the run event log. */
  appendRunStep(runId: string, seq: number, type: string, payload: unknown): Promise<void>;
  /** Lists run events, optionally returning only events after the supplied sequence. */
  listRunSteps(runId: string, sinceSeq?: number): Promise<RunStepRecord[]>;
  /** Persists a pending approval request for a run. */
  createApproval(request: ApprovalRequest): Promise<void>;
  /** Returns the current pending approval request for a run, if one exists. */
  getPendingApproval(runId: string): Promise<ApprovalRequest | undefined>;
  /** Records the human decision for a run approval. */
  decideApproval(runId: string, decision: ApprovalDecision): Promise<void>;
}

/**
 * Runtime services and policy supplied to an orchestrator for a single run.
 */
export type RunContext = {
  /** Logger scoped to the backend runtime. */
  logger: LoggerService;
  /** Registry of tools available to the current run. */
  toolRegistry: ToolRegistry;
  /** Language model selected for the current agent run. */
  model: BaseLLM | BaseChatModel;
  /** Optional system prompt applied by the orchestrator when calling the model. */
  systemPrompt?: string;
  /** Optional actor identity for tool context, audit logs, and session ownership. */
  identity?: string;
  /** Optional cancellation signal for long-running model or tool work. */
  signal?: AbortSignal;
  /** Optional session memory store for conversation history. */
  sessionStore?: SessionStore;
  /** Optional checkpoint store for resumable orchestration. */
  checkpointStore?: CheckpointStore;
  /** Optional run store for lifecycle persistence and event replay. */
  runStore?: RunStore;
  /** Optional sink for artifacts emitted by orchestrators. */
  artifactSink?: ArtifactSink;
  /** Optional sink for write-action audit records. */
  auditLogSink?: AuditLogSink;
  /** Optional runtime hardening limits and retry policy. */
  hardening?: {
    /** Maximum run duration in milliseconds before cancellation. */
    timeoutMs?: number;
    /** Maximum number of retries for retryable orchestration failures. */
    maxRetries?: number;
    /** Base delay in milliseconds between retries. */
    retryBackoffMs?: number;
    /** Maximum total tokens allowed for a run before it is stopped. */
    maxTotalTokens?: number;
  };
  /** Memory mode selected for the current agent. */
  memory?: 'none' | 'session';
};

/**
 * Event stream emitted by orchestrators and consumed by controllers/runtime stores.
 */
export type AgentEvent =
  /** Lifecycle step transition for a named orchestration node. */
  | {
      type: 'step';
      /** Step transition payload. */
      data: { runId: string; seq: number; node: string; phase: 'enter' | 'exit' };
    }
  /** Streaming model token or text chunk. */
  | { type: 'token'; data: { runId: string; text: string } }
  /** Tool invocation request emitted before a tool is executed. */
  | { type: 'tool_call'; data: { runId: string; tool: string; args: unknown } }
  /** Tool invocation result emitted after a tool completes or fails. */
  | {
      type: 'tool_result';
      data: {
        /** Run associated with the tool result. */
        runId: string;
        /** Tool identifier. */
        tool: string;
        /** Whether the tool completed successfully. */
        ok: boolean;
        /** Optional short summary suitable for event logs and UI display. */
        summary?: string;
        /** Optional raw or structured tool output. */
        output?: unknown;
      };
    }
  /** Token usage totals reported by the model or orchestrator. */
  | {
      type: 'usage';
      /** Token usage payload for the run. */
      data: { runId: string; input: number; output: number; total: number };
    }
  /** Request for human approval before continuing a run. */
  | {
      type: 'approval_request';
      /** Approval request payload emitted to clients and run stores. */
      data: { runId: string; approvalId: string; reason: string; effect: 'read' | 'write' };
    }
  /** Artifact produced by the run. */
  | {
      type: 'artifact';
      /** Artifact payload emitted to clients and artifact sinks. */
      data: { runId: string; kind: string; url?: string; ref?: string };
    }
  /** Successful completion marker for a run. */
  | { type: 'done'; data: { runId: string; sessionId?: string } }
  /** Non-recoverable error marker for a run. */
  | { type: 'error'; data: { runId: string; message: string } };

/**
 * Orchestrates an agent run and emits lifecycle, token, tool, and terminal events.
 */
export interface Orchestrator {
  /** Starts a run and returns its event stream. */
  run(input: AgentRunInput, ctx: RunContext): AsyncIterable<AgentEvent>;
  /** Resumes a paused run after an approval decision, when supported. */
  resume?(
    runId: string,
    decision: ApprovalDecision,
    ctx: RunContext,
  ): AsyncIterable<AgentEvent>;
}
