/*
 * Copyright 2026 Webstack Builders, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { LoggerService } from '@backstage/backend-plugin-api';
import { BaseLLM } from '@langchain/core/language_models/llms';
import { BaseChatModel } from '@langchain/core/language_models/chat_models';
import { ToolRegistry } from './tool';
import { SessionStore } from './session';
import { SourceId, EntityFilterShape } from './source';

/**
 * Input required to start an agent run.
 */
export type AgentRunInput = {
  /** Unique run identifier generated by the caller or controller. */
  runId: string;
  /** Agent identifier to execute. */
  agentId: string;
  /** Optional idempotency key used to deduplicate external trigger requests. */
  idempotencyKey?: string;
  /** Optional trigger name or source that initiated the run. */
  trigger?: string;
  /** User and retrieval inputs supplied to the agent. */
  input: {
    /** Natural-language task or question for the agent. */
    query: string;
    /** Source to use for retrieval augmentation. */
    source: SourceId;
    /** Optional conversation session ID for memory-enabled agents. */
    sessionId?: string;
    /** Optional entity/document filter passed to retrieval tools. */
    entityFilter?: EntityFilterShape;
  };
};

/**
 * Store for resumable orchestration state.
 */
export interface CheckpointStore {
  /** Saves arbitrary checkpoint state for a run. */
  save(runId: string, state: unknown): Promise<void>;
  /** Loads checkpoint state for a run, or `undefined` when no checkpoint exists. */
  load<T = unknown>(runId: string): Promise<T | undefined>;
}

/**
 * Persisted summary record for an agent run.
 */
export type RunRecord = {
  /** Unique run identifier. */
  id: string;
  /** Agent executed by the run. */
  agentId: string;
  /** Optional session associated with the run. */
  sessionId?: string;
  /** Current lifecycle status for the run. */
  status: 'running' | 'paused' | 'done' | 'error';
  /** Optional trigger source that started the run. */
  trigger?: string;
  /** Optional idempotency key used to deduplicate run creation. */
  idempotencyKey?: string;
};

/**
 * Persisted event emitted during an agent run.
 */
export type RunStepRecord = {
  /** Monotonic sequence number for replaying events in order. */
  seq: number;
  /** Event type name. */
  type: string;
  /** Serialized event payload. */
  payload: unknown;
};

/**
 * Artifact produced by an agent run.
 */
export type Artifact = {
  /** Unique artifact identifier. */
  id: string;
  /** Run that produced the artifact. */
  runId: string;
  /** Artifact category, such as `doc`, `draft`, or `final_answer`. */
  kind: string;
  /** Optional stable reference name for the artifact. */
  ref?: string;
  /** Optional URL where the artifact can be retrieved. */
  url?: string;
};

/**
 * Sink for recording artifacts produced by runs.
 */
export interface ArtifactSink {
  /** Persists or forwards an artifact record. */
  record(artifact: Artifact): Promise<void>;
}

/**
 * Audit record for write actions and approval decisions.
 */
export type AuditLogEntry = {
  /** Unique audit entry identifier. */
  id: string;
  /** Run associated with the audited action. */
  runId: string;
  /** Agent associated with the audited action. */
  agentId: string;
  /** Action name, such as `write_tool_call` or `approval_approved`. */
  action: string;
  /** Optional tool ID involved in the action. */
  toolId?: string;
  /** Optional sanitized payload for diagnostics and compliance review. */
  payload?: unknown;
  /** Optional actor identity that initiated or approved the action. */
  actor?: string;
};

/**
 * Sink for recording auditable write-related actions.
 */
export interface AuditLogSink {
  /** Records an auditable write action, approval decision, or artifact write. */
  recordWriteAction(entry: AuditLogEntry): Promise<void>;
}

/**
 * Human decision for a pending approval request.
 */
export type ApprovalDecision = {
  /** Whether the requested action is allowed to continue. */
  status: 'approved' | 'rejected';
  /** Optional reviewer note explaining the decision. */
  note?: string;
  /** Optional identity of the reviewer who made the decision. */
  decidedBy?: string;
};

/**
 * Pending approval request emitted when an agent needs human authorization.
 */
export type ApprovalRequest = {
  /** Unique approval identifier. */
  id: string;
  /** Run waiting on this approval. */
  runId: string;
  /** Human-readable reason approval is required. */
  reason: string;
  /** Effect level of the pending action. */
  effect: 'read' | 'write';
};

/**
 * Store for run lifecycle, event replay, and approval state.
 */
export interface RunStore {
  /** Creates the initial persisted record for a run. */
  createRun(record: RunRecord): Promise<void>;
  /** Returns a run record by ID, or `undefined` when not found. */
  getRun(runId: string): Promise<RunRecord | undefined>;
  /** Returns a run previously created with the idempotency key, if any. */
  findRunByIdempotencyKey(key: string): Promise<RunRecord | undefined>;
  /** Updates the lifecycle status for a run. */
  updateRunStatus(runId: string, status: RunRecord['status']): Promise<void>;
  /** Appends an event payload to the run event log. */
  appendRunStep(runId: string, seq: number, type: string, payload: unknown): Promise<void>;
  /** Lists run events, optionally returning only events after the supplied sequence. */
  listRunSteps(runId: string, sinceSeq?: number): Promise<RunStepRecord[]>;
  /** Persists a pending approval request for a run. */
  createApproval(request: ApprovalRequest): Promise<void>;
  /** Returns the current pending approval request for a run, if one exists. */
  getPendingApproval(runId: string): Promise<ApprovalRequest | undefined>;
  /** Records the human decision for a run approval. */
  decideApproval(runId: string, decision: ApprovalDecision): Promise<void>;
}

/**
 * Runtime services and policy supplied to an orchestrator for a single run.
 */
export type RunContext = {
  /** Logger scoped to the backend runtime. */
  logger: LoggerService;
  /** Registry of tools available to the current run. */
  toolRegistry: ToolRegistry;
  /** Language model selected for the current agent run. */
  model: BaseLLM | BaseChatModel;
  /** Optional system prompt applied by the orchestrator when calling the model. */
  systemPrompt?: string;
  /** Optional actor identity for tool context, audit logs, and session ownership. */
  identity?: string;
  /** Optional cancellation signal for long-running model or tool work. */
  signal?: AbortSignal;
  /** Optional session memory store for conversation history. */
  sessionStore?: SessionStore;
  /** Optional checkpoint store for resumable orchestration. */
  checkpointStore?: CheckpointStore;
  /** Optional run store for lifecycle persistence and event replay. */
  runStore?: RunStore;
  /** Optional sink for artifacts emitted by orchestrators. */
  artifactSink?: ArtifactSink;
  /** Optional sink for write-action audit records. */
  auditLogSink?: AuditLogSink;
  /** Optional runtime hardening limits and retry policy. */
  hardening?: {
    /** Maximum run duration in milliseconds before cancellation. */
    timeoutMs?: number;
    /** Maximum number of retries for retryable orchestration failures. */
    maxRetries?: number;
    /** Base delay in milliseconds between retries. */
    retryBackoffMs?: number;
    /** Maximum total tokens allowed for a run before it is stopped. */
    maxTotalTokens?: number;
  };
  /** Memory mode selected for the current agent. */
  memory?: 'none' | 'session';
};

/**
 * Event stream emitted by orchestrators and consumed by controllers/runtime stores.
 */
export type AgentEvent =
  /** Lifecycle step transition for a named orchestration node. */
  | {
      type: 'step';
      /** Step transition payload. */
      data: { runId: string; seq: number; node: string; phase: 'enter' | 'exit' };
    }
  /** Streaming model token or text chunk. */
  | { type: 'token'; data: { runId: string; text: string } }
  /** Tool invocation request emitted before a tool is executed. */
  | { type: 'tool_call'; data: { runId: string; tool: string; args: unknown } }
  /** Tool invocation result emitted after a tool completes or fails. */
  | {
      type: 'tool_result';
      data: {
        /** Run associated with the tool result. */
        runId: string;
        /** Tool identifier. */
        tool: string;
        /** Whether the tool completed successfully. */
        ok: boolean;
        /** Optional short summary suitable for event logs and UI display. */
        summary?: string;
        /** Optional raw or structured tool output. */
        output?: unknown;
      };
    }
  /** Token usage totals reported by the model or orchestrator. */
  | {
      type: 'usage';
      /** Token usage payload for the run. */
      data: { runId: string; input: number; output: number; total: number };
    }
  /** Request for human approval before continuing a run. */
  | {
      type: 'approval_request';
      /** Approval request payload emitted to clients and run stores. */
      data: { runId: string; approvalId: string; reason: string; effect: 'read' | 'write' };
    }
  /** Artifact produced by the run. */
  | {
      type: 'artifact';
      /** Artifact payload emitted to clients and artifact sinks. */
      data: { runId: string; kind: string; url?: string; ref?: string };
    }
  /** Successful completion marker for a run. */
  | { type: 'done'; data: { runId: string; sessionId?: string } }
  /** Non-recoverable error marker for a run. */
  | { type: 'error'; data: { runId: string; message: string } };

/**
 * Orchestrates an agent run and emits lifecycle, token, tool, and terminal events.
 */
export interface Orchestrator {
  /** Starts a run and returns its event stream. */
  run(input: AgentRunInput, ctx: RunContext): AsyncIterable<AgentEvent>;
  /** Resumes a paused run after an approval decision, when supported. */
  resume?(
    runId: string,
    decision: ApprovalDecision,
    ctx: RunContext,
  ): AsyncIterable<AgentEvent>;
}
